from dataclasses import dataclass
from decimal import Decimal


@dataclass(frozen=True, slots=True)
class Micronutrient:
    yazio_id: str
    metric_type: str
    label: str
    category: str
    unit: str
    eu_nrv: Decimal | None
    healthkit_types: tuple[str, ...] = ()


# EU nutrient reference values (NRV) for adults from Annex XIII, Part A,
# Regulation (EU) No 1169/2011. Choline has no EU NRV in that table.
MICRONUTRIENTS = (
    Micronutrient(
        "vitamin.a",
        "vitamin_a_ug",
        "Vitamin A",
        "vitamin",
        "ug",
        Decimal("800"),
        ("dietary_vitamin_a", "HKQuantityTypeIdentifierDietaryVitaminA"),
    ),
    Micronutrient(
        "vitamin.b1",
        "thiamin_mg",
        "Vitamin B1 (Thiamin)",
        "vitamin",
        "mg",
        Decimal("1.1"),
        ("dietary_thiamin", "HKQuantityTypeIdentifierDietaryThiamin"),
    ),
    Micronutrient(
        "vitamin.b2",
        "riboflavin_mg",
        "Vitamin B2 (Riboflavin)",
        "vitamin",
        "mg",
        Decimal("1.4"),
        ("dietary_riboflavin", "HKQuantityTypeIdentifierDietaryRiboflavin"),
    ),
    Micronutrient(
        "vitamin.b3",
        "niacin_mg",
        "Vitamin B3 (Niacin)",
        "vitamin",
        "mg",
        Decimal("16"),
        ("dietary_niacin", "HKQuantityTypeIdentifierDietaryNiacin"),
    ),
    Micronutrient(
        "vitamin.b5",
        "pantothenic_acid_mg",
        "Vitamin B5 (Pantothensäure)",
        "vitamin",
        "mg",
        Decimal("6"),
        (
            "dietary_pantothenic_acid",
            "HKQuantityTypeIdentifierDietaryPantothenicAcid",
        ),
    ),
    Micronutrient(
        "vitamin.b6",
        "vitamin_b6_mg",
        "Vitamin B6",
        "vitamin",
        "mg",
        Decimal("1.4"),
        ("dietary_vitamin_b6", "HKQuantityTypeIdentifierDietaryVitaminB6"),
    ),
    Micronutrient(
        "vitamin.b7",
        "biotin_ug",
        "Vitamin B7 (Biotin)",
        "vitamin",
        "ug",
        Decimal("50"),
        ("dietary_biotin", "HKQuantityTypeIdentifierDietaryBiotin"),
    ),
    Micronutrient(
        "vitamin.b11",
        "folate_ug",
        "Vitamin B11 (Folat)",
        "vitamin",
        "ug",
        Decimal("200"),
        ("dietary_folate", "HKQuantityTypeIdentifierDietaryFolate"),
    ),
    Micronutrient(
        "vitamin.b12",
        "vitamin_b12_ug",
        "Vitamin B12",
        "vitamin",
        "ug",
        Decimal("2.5"),
        ("dietary_vitamin_b12", "HKQuantityTypeIdentifierDietaryVitaminB12"),
    ),
    Micronutrient(
        "vitamin.c",
        "vitamin_c_mg",
        "Vitamin C",
        "vitamin",
        "mg",
        Decimal("80"),
        ("dietary_vitamin_c", "HKQuantityTypeIdentifierDietaryVitaminC"),
    ),
    Micronutrient(
        "vitamin.d",
        "vitamin_d_ug",
        "Vitamin D",
        "vitamin",
        "ug",
        Decimal("5"),
        ("dietary_vitamin_d", "HKQuantityTypeIdentifierDietaryVitaminD"),
    ),
    Micronutrient(
        "vitamin.e",
        "vitamin_e_mg",
        "Vitamin E",
        "vitamin",
        "mg",
        Decimal("12"),
        ("dietary_vitamin_e", "HKQuantityTypeIdentifierDietaryVitaminE"),
    ),
    Micronutrient(
        "vitamin.k",
        "vitamin_k_ug",
        "Vitamin K",
        "vitamin",
        "ug",
        Decimal("75"),
        ("dietary_vitamin_k", "HKQuantityTypeIdentifierDietaryVitaminK"),
    ),
    Micronutrient(
        "mineral.calcium",
        "calcium_mg",
        "Calcium",
        "mineral",
        "mg",
        Decimal("800"),
        ("dietary_calcium", "HKQuantityTypeIdentifierDietaryCalcium"),
    ),
    Micronutrient(
        "mineral.iron",
        "iron_mg",
        "Eisen",
        "mineral",
        "mg",
        Decimal("14"),
        ("dietary_iron", "HKQuantityTypeIdentifierDietaryIron"),
    ),
    Micronutrient(
        "mineral.potassium",
        "potassium_mg",
        "Kalium",
        "mineral",
        "mg",
        Decimal("2000"),
        ("dietary_potassium", "HKQuantityTypeIdentifierDietaryPotassium"),
    ),
    Micronutrient(
        "mineral.magnesium",
        "magnesium_mg",
        "Magnesium",
        "mineral",
        "mg",
        Decimal("375"),
        ("dietary_magnesium", "HKQuantityTypeIdentifierDietaryMagnesium"),
    ),
    Micronutrient(
        "mineral.phosphorus",
        "phosphorus_mg",
        "Phosphor",
        "mineral",
        "mg",
        Decimal("700"),
        ("dietary_phosphorus", "HKQuantityTypeIdentifierDietaryPhosphorus"),
    ),
    Micronutrient(
        "mineral.zinc",
        "zinc_mg",
        "Zink",
        "mineral",
        "mg",
        Decimal("10"),
        ("dietary_zinc", "HKQuantityTypeIdentifierDietaryZinc"),
    ),
    Micronutrient(
        "mineral.copper",
        "copper_mg",
        "Kupfer",
        "mineral",
        "mg",
        Decimal("1"),
        ("dietary_copper", "HKQuantityTypeIdentifierDietaryCopper"),
    ),
    Micronutrient(
        "mineral.manganese",
        "manganese_mg",
        "Mangan",
        "mineral",
        "mg",
        Decimal("2"),
        ("dietary_manganese", "HKQuantityTypeIdentifierDietaryManganese"),
    ),
    Micronutrient(
        "mineral.selenium",
        "selenium_ug",
        "Selen",
        "mineral",
        "ug",
        Decimal("55"),
        ("dietary_selenium", "HKQuantityTypeIdentifierDietarySelenium"),
    ),
    Micronutrient(
        "mineral.iodine",
        "iodine_ug",
        "Jod",
        "mineral",
        "ug",
        Decimal("150"),
        ("dietary_iodine", "HKQuantityTypeIdentifierDietaryIodine"),
    ),
    Micronutrient(
        "mineral.fluoride",
        "fluoride_mg",
        "Fluorid",
        "mineral",
        "mg",
        Decimal("3.5"),
        ("dietary_fluoride", "HKQuantityTypeIdentifierDietaryFluoride"),
    ),
    Micronutrient(
        "mineral.chlorine",
        "chloride_mg",
        "Chlorid",
        "mineral",
        "mg",
        Decimal("800"),
        ("dietary_chloride", "HKQuantityTypeIdentifierDietaryChloride"),
    ),
    Micronutrient(
        "mineral.choline",
        "choline_mg",
        "Cholin",
        "mineral",
        "mg",
        None,
        ("dietary_choline", "HKQuantityTypeIdentifierDietaryCholine"),
    ),
)

MICRONUTRIENT_BY_YAZIO_ID = {item.yazio_id: item for item in MICRONUTRIENTS}
MICRONUTRIENT_BY_METRIC = {item.metric_type: item for item in MICRONUTRIENTS}
MICRONUTRIENT_METRIC_TYPES = frozenset(MICRONUTRIENT_BY_METRIC)
YAZIO_MICRONUTRIENT_IDS = tuple(item.yazio_id for item in MICRONUTRIENTS)
