from .aggregation import (
    aggregate_contributions,
    aggregate_coverage,
    aggregate_lineage,
    aggregate_presence,
    aggregate_resolution,
)
from .contracts import (
    AggregatedMetric,
    EventReconstructionCandidate,
    MetricContribution,
    ProviderCandidate,
    SummaryCandidate,
    build_event_candidate,
    build_summary_candidate,
)
from .daily_reader import resolve_daily_nutrient, resolve_daily_nutrients
from .discovery import (
    NutritionProviderDiscovery,
    NutritionProviderIdentity,
    NutritionProviderMetadata,
    NutritionProviderMetadataSet,
    ProviderDiscoveryEvidence,
    ProviderDiscoveryResolver,
    discover_nutrition_provider_metadata,
    discover_nutrition_providers,
)
from .eligibility import is_candidate_eligible, is_summary_usable
from .metrics import (
    CANONICAL_NUTRITION_METRICS,
    DAILY_PROJECTION_METRICS,
    MetricDefinition,
    canonical_unit,
    is_known_metric,
    is_unsupported_metric,
    metric_definition,
)
from .parity import ParityDiagnostic, compare_decimal_parity
from .period_reader import (
    MAX_PROVIDER_PERIOD_DAYS,
    NutritionPeriodResolver,
    PeriodCandidates,
    iter_provider_period_chunks,
    resolve_provider_period,
)
from .providers import (
    NUTRIENT_READ_PROVIDER_RESOLVERS,
    PROVIDER_RESOLVERS,
    NutritionProviderResolver,
    ProviderCandidateContractError,
    ProviderNotAvailableError,
    YazioProviderResolver,
    collect_provider_candidates,
    resolve_provider_metric,
)
from .reasons import EvidenceKind, ReasonCode
from .resolver import resolve_event_vs_summary
from .sources import ProviderSourceBindings, ProviderSourceInstance

__all__ = [
    "CANONICAL_NUTRITION_METRICS",
    "DAILY_PROJECTION_METRICS",
    "MAX_PROVIDER_PERIOD_DAYS",
    "NUTRIENT_READ_PROVIDER_RESOLVERS",
    "PROVIDER_RESOLVERS",
    "AggregatedMetric",
    "EventReconstructionCandidate",
    "EvidenceKind",
    "MetricContribution",
    "MetricDefinition",
    "NutritionPeriodResolver",
    "NutritionProviderDiscovery",
    "NutritionProviderIdentity",
    "NutritionProviderMetadata",
    "NutritionProviderMetadataSet",
    "NutritionProviderResolver",
    "ParityDiagnostic",
    "PeriodCandidates",
    "ProviderCandidate",
    "ProviderCandidateContractError",
    "ProviderDiscoveryEvidence",
    "ProviderDiscoveryResolver",
    "ProviderNotAvailableError",
    "ProviderSourceBindings",
    "ProviderSourceInstance",
    "ReasonCode",
    "SummaryCandidate",
    "YazioProviderResolver",
    "aggregate_contributions",
    "aggregate_coverage",
    "aggregate_lineage",
    "aggregate_presence",
    "aggregate_resolution",
    "build_event_candidate",
    "build_summary_candidate",
    "canonical_unit",
    "collect_provider_candidates",
    "compare_decimal_parity",
    "discover_nutrition_provider_metadata",
    "discover_nutrition_providers",
    "is_candidate_eligible",
    "is_known_metric",
    "is_summary_usable",
    "is_unsupported_metric",
    "iter_provider_period_chunks",
    "metric_definition",
    "resolve_daily_nutrient",
    "resolve_daily_nutrients",
    "resolve_event_vs_summary",
    "resolve_provider_metric",
    "resolve_provider_period",
]
